---
- name: Database Setup
  hosts: dbservers
  remote_user: ubuntu
  become: yes
  roles:
    - common
    - database

- name: Webserver Setup
  hosts: webservers
  remote_user: ubuntu
  become: yes
  roles:
    - common
    - web
